/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Asus
 *
 */




public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DasboardFrame
     */
    private int usuarioId;
    public DashboardFrame(int usuarioId) {
        initComponents();
        
        this.usuarioId = usuarioId;
        setTitle("Spotifei - Dashboard");
        setSize(800, 600);
        setLayout(null);
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null); // Centraliza a janela

    // ==== Título ====
        JLabel titleLabel = new JLabel("SPOTIFEI", SwingConstants.CENTER);
        titleLabel.setBounds(0, 20, 800, 50);
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 48));
        titleLabel.setForeground(new Color(30, 215, 96));
        add(titleLabel);

        JLabel dashboardLabel = new JLabel("DASHBOARD", SwingConstants.CENTER);
        dashboardLabel.setBounds(0, 80, 800, 40);
        dashboardLabel.setFont(new Font("SansSerif", Font.BOLD, 32));
        dashboardLabel.setForeground(new Color(30, 215, 96));
        add(dashboardLabel);

    // ==== Botões ====
        JButton musicButton = new JButton("Músicas");
        musicButton.setBounds(150, 180, 200, 50);
        musicButton.setBackground(new Color(30, 215, 96));
        musicButton.setForeground(Color.BLACK);
        add(musicButton);

        JButton playlistButton = new JButton("Playlists");
        playlistButton.setBounds(450, 180, 200, 50);
        playlistButton.setBackground(new Color(30, 215, 96));
        playlistButton.setForeground(Color.BLACK);
        add(playlistButton);

        JButton artistButton = new JButton("Artistas");
        artistButton.setBounds(150, 260, 200, 50);
        artistButton.setBackground(new Color(30, 215, 96));
        artistButton.setForeground(Color.BLACK);
        add(artistButton);

        JButton historyButton = new JButton("Histórico");
        historyButton.setBounds(450, 260, 200, 50);
        historyButton.setBackground(new Color(30, 215, 96));
        historyButton.setForeground(Color.BLACK);
        add(historyButton);

    // ==== Ações dos Botões ====
        musicButton.addActionListener(e -> {
            new MusicaFrame().setVisible(true);
        });

        playlistButton.addActionListener(e -> {
            new PlaylistFrame().setVisible(true);
        });

        artistButton.addActionListener(e -> {
            new ArtistaFrame().setVisible(true);
        });

        historyButton.addActionListener(e -> JOptionPane.showMessageDialog(null, "Abrir tela de Histórico."));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            int usuarioId = 1; // ID de teste, depois vamos colocar o correto
            new DashboardFrame(usuarioId).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
